# 01 — FCA workbook profiling review

This notebook reviews generated profiling outputs only. All profiling logic lives in `src/customer_harm/profiling`; raw workbooks are never written. Run `profile-fca-workbooks` before opening this notebook.

In [1]:
from pathlib import Path
import json
import pandas as pd

PROFILE_DIR = Path('../data/interim/profiling')
workbooks = pd.read_csv(PROFILE_DIR / 'workbook_inventory.csv')
sheets = pd.read_csv(PROFILE_DIR / 'sheet_inventory.csv')
columns = pd.read_csv(PROFILE_DIR / 'column_profiles.csv')
headers = pd.read_csv(PROFILE_DIR / 'header_detection_results.csv')
schema = pd.read_csv(PROFILE_DIR / 'schema_comparison.csv')
warnings = pd.read_csv(PROFILE_DIR / 'profiling_warnings.csv')
formats = pd.read_csv(PROFILE_DIR / 'cell_format_profiles.csv')
product_groups = pd.read_csv(PROFILE_DIR / 'product_group_inventory.csv')
product_group_changes = pd.read_csv(PROFILE_DIR / 'product_group_comparison.csv')
taxonomy = pd.read_csv(PROFILE_DIR / 'product_taxonomy_inventory.csv')
taxonomy_changes = pd.read_csv(PROFILE_DIR / 'product_taxonomy_comparison.csv')
definitions = pd.read_csv(PROFILE_DIR / 'reporting_definitions.csv')
definition_changes = pd.read_csv(PROFILE_DIR / 'reporting_definition_comparison.csv')
review_register = pd.read_csv(PROFILE_DIR / 'profiling_review_register.csv')
review_gate = json.loads((PROFILE_DIR / 'profiling_review_gate.json').read_text())

## Profiling review gate

In [2]:
display(pd.DataFrame([review_gate]))
display(review_register[['review_item_id', 'category', 'scope', 'severity', 'blocks_extraction', 'decision_status', 'recommended_action']])

                       generated_at  ...                               decision_source
0  2026-07-18T13:10:32.699971+00:00  ...  data/mappings/profiling_review_decisions.csv

[1 rows x 9 columns]

    review_item_id  ...                                 recommended_action
0   REV-A384BF1B33  ...         Retain hashes and exact-period validation.
1   REV-E86CDF0785  ...  Keep immutable raw names and use manifest sour...
2   REV-7FEC48E030  ...        Confirm row 9 as the Notes taxonomy header.
3   REV-8B2996CFDD  ...  Keep immutable raw names and use manifest sour...
4   REV-A490218956  ...        Confirm row 9 as the Notes taxonomy header.
5   REV-C3A87947AA  ...  Keep immutable raw names and use manifest sour...
6   REV-CE02A4F68C  ...        Confirm row 9 as the Notes taxonomy header.
7   REV-A51F5C5CEF  ...  Keep immutable raw names and use manifest sour...
8   REV-65844D44C3  ...        Confirm row 9 as the Notes taxonomy header.
9   REV-E0FB2DF0B3  ...  Keep immutable raw names and use manifest sour...
10  REV-0BB8894C13  ...  Accept value-based bounds while retaining the ...
11  REV-CC418B08B4  ...        Confirm row 9 as the Notes taxonomy header.
12  REV-140CBA92AC  ...  Keep immutable raw names and use manifest sour...
13  REV-F1ED3817F3  ...  Determine the meaning of the text value and un...
14  REV-7D1451CAB0  ...  Keep immutable raw names and use manifest sour...
15  REV-6853FA8892  ...        Confirm row 9 as the Notes taxonomy header.
16  REV-59BFF984E7  ...  Keep immutable raw names and use manifest sour...
17  REV-6526CD6DA2  ...  Keep immutable raw names and use manifest sour...
18  REV-DE070F74FA  ...  Confirm the marker meaning and document its fu...
19  REV-DD5E937D6A  ...  Keep immutable raw names and use manifest sour...
20  REV-D7590B79E4  ...  Inspect the affected error cells and define wh...
21  REV-189F967382  ...  Inspect the affected error cells and define wh...
22  REV-EE0C638468  ...  Review evidence and approve canonical mappings...
23  REV-EB30419D16  ...  Review evidence and approve canonical mappings...
24  REV-23981CDAE7  ...  Review evidence and approve canonical mappings...
25  REV-F65BAA3049  ...  Review evidence and approve canonical mappings...
26  REV-4D13ADA54B  ...  Confirm whether omitted per-1,000 wording chan...
27  REV-2D18373974  ...  Approve or reject an explicit reviewed mapping...
28  REV-3AF425FDE7  ...  Use the latest prior taxonomy only if explicit...
29  REV-D0F4A14413  ...  Review publication dates and stale period word...

[30 rows x 7 columns]

## Product definitions and reporting wording

In [3]:
display(product_groups.groupby(['reporting_period', 'label_type']).size().unstack(fill_value=0))
display(product_group_changes)
display(taxonomy.groupby(['reporting_period', 'inherited_product_group']).size().unstack(fill_value=0))
display(taxonomy_changes)
display(definition_changes[['previous_period', 'current_period', 'definition_key', 'change_type']])

label_type        product_group  total  unexpected_blank_header
reporting_period
2021-H1                      34      5                        0
2021-H2                      34      0                        0
2022-H1                      34      0                        0
2022-H2                      34      5                        0
2023-H1                      34      0                        0
2023-H2                      34      0                        1
2024-H1                      34      0                        0
2024-H2                      34      0                        0
2025-H1                      34      0                        0
2025-H2                      34      5                        0

   previous_period  ...                                      current_value
0          2021-H1  ...                            Decumulation & pensions
1          2021-H1  ...                                                NaN
2          2021-H1  ...                                       Home finance
3          2021-H1  ...                                                NaN
4          2021-H1  ...                        Insurance & pure protection
5          2021-H1  ...                                                NaN
6          2021-H1  ...                                        Investments
7          2021-H1  ...                                                NaN
8          2021-H1  ...                           Banking and credit cards
9          2021-H1  ...                                                NaN
10         2021-H1  ...                            Decumulation & pensions
11         2021-H1  ...                                                NaN
12         2021-H1  ...                                       Home finance
13         2021-H1  ...                                                NaN
14         2021-H1  ...                        Insurance & pure protection
15         2021-H1  ...                                                NaN
16         2021-H1  ...                                        Investments
17         2021-H1  ...                                                NaN
18         2021-H2  ...  Decumulation & pensions (per 1,000 policies sold)
19         2021-H2  ...                            per 1,000 policies sold
20         2021-H2  ...                     Home finance (per 1,000 sales)
21         2021-H2  ...                                    per 1,000 sales
22         2021-H2  ...  Insurance & pure protection (per 1,000 policie...
23         2021-H2  ...                            per 1,000 policies sold
24         2021-H2  ...      Investments (per 1,000 sales or transactions)
25         2021-H2  ...                    per 1,000 sales or transactions
26         2021-H2  ...      Banking and credit cards (per 1,000 accounts)
27         2021-H2  ...                                 per 1,000 accounts
28         2021-H2  ...  Decumulation & pensions (per 1,000 policies in...
29         2021-H2  ...                        per 1,000 policies in force

[30 rows x 7 columns]
[Preview limited to 30 of 54 rows]

inherited_product_group  banking and credit cards  ...  investments
reporting_period                                   ...
2021-H1                                         6  ...           15
2021-H2                                         6  ...           15
2022-H1                                         6  ...           15
2022-H2                                         6  ...           15
2023-H1                                         6  ...           15
2024-H1                                         6  ...           15

[6 rows x 5 columns]

  previous_period current_period  ... previous_value  current_value
0         2023-H1        2023-H2  ...           True          False
1         2023-H2        2024-H1  ...          False           True
2         2024-H1        2024-H2  ...           True          False
3         2024-H2        2025-H1  ...          False          False
4         2025-H1        2025-H2  ...          False          False

[5 rows x 7 columns]

  previous_period  ...                       change_type
0         2022-H1  ...           definition_text_changed
1         2022-H2  ...           definition_text_changed
2         2023-H1  ...  definition_reference_unavailable
3         2023-H2  ...  definition_reference_unavailable
4         2024-H1  ...  definition_reference_unavailable
5         2024-H2  ...  definition_reference_unavailable
6         2025-H1  ...  definition_reference_unavailable

[7 rows x 4 columns]

## Source coverage and processing status

In [4]:
display(workbooks[['reporting_period', 'source_file_name', 'sheet_count', 'rows_extracted', 'processing_status', 'warning_count']])
display(sheets.groupby('reporting_period').agg(sheets=('sheet', 'size'), rows=('data_rows', 'sum'), columns=('data_columns', 'sum')))

  reporting_period  ... warning_count
0          2021-H1  ...             2
1          2021-H2  ...             2
2          2022-H1  ...             2
3          2022-H2  ...             2
4          2023-H1  ...             3
5          2023-H2  ...             2
6          2024-H1  ...             2
7          2024-H2  ...             1
8          2025-H1  ...             2
9          2025-H2  ...             3

[10 rows x 6 columns]

                  sheets   rows  columns
reporting_period
2021-H1               12   1977       86
2021-H2               12   1852       81
2022-H1               12   1894       81
2022-H2               12   1902       87
2023-H1               12   2045       82
2023-H2               11   1924       82
2024-H1               12   2003       83
2024-H2               11   1838       81
2025-H1               11  10280       81
2025-H2               11   1640       86

## Header detection requiring review

In [5]:
selected = headers.query('selected == True')
display(selected.sort_values('score').head(20)[['reporting_period', 'sheet', 'row_number', 'score', 'values']])
display(sheets.query('duplicate_column_count > 0 or empty_leading_rows > 0')[['reporting_period', 'sheet', 'header_row', 'duplicate_columns', 'empty_leading_rows']])

     reporting_period  ...                                             values
399           2021-H1  ...               Product group | Product/service name
1326          2022-H1  ...               Product group | Product/service name
1794          2022-H2  ...               Product group | Product/service name
2248          2023-H1  ...               Product group | Product/service name
3118          2024-H1  ...               Product group | Product/service name
860           2021-H2  ...               Product group | Product/service name
756           2021-H2  ...            Firm Name | Other trading names | Group
1217          2022-H1  ...            Firm Name | Other trading names | Group
1683          2022-H2  ...            Firm Name | Other trading names | Group
3099          2024-H1  ...  Firm Name | Reporting period | Other firms inc...
1257          2022-H1  ...  Firm Name | Reporting period | Other firms inc...
1297          2022-H1  ...  Firm Name | Reporting period | Other firms inc...
3963          2025-H1  ...  Firm Name | Reporting period | Other firms inc...
1723          2022-H2  ...  Firm Name | Reporting period | Other firms inc...
1763          2022-H2  ...  Firm Name | Reporting period | Other firms inc...
3924          2025-H1  ...  Firm Name | Reporting period | Other firms inc...
4333          2025-H2  ...  Firm Name | Other firms included in return | R...
2231          2023-H1  ...  Firm name | Reporting period | Other firms inc...
3555          2024-H2  ...  Firm Name | Reporting period | Other firms inc...
2645          2023-H2  ...  Firm Name | Reporting period | Other firms inc...

[20 rows x 5 columns]

   reporting_period  sheet  header_row duplicate_columns  empty_leading_rows
11          2021-H1  Notes           9                []                   1
23          2021-H2  Notes           9                []                   1
35          2022-H1  Notes           9                []                   1
47          2022-H2  Notes           9                []                   1
59          2023-H1  Notes           9                []                   1
82          2024-H1  Notes           9                []                   1

## Missingness and workbook formatting

In [6]:
display(columns.query('row_count > 0').nlargest(25, 'missing_percent')[['reporting_period', 'sheet', 'column', 'semantic_type', 'null_count', 'blank_string_count', 'missing_percent']])
display(columns.groupby(['reporting_period', 'semantic_type']).size().unstack(fill_value=0))
marker_columns = ['missing_marker_count', 'suppressed_marker_count', 'not_applicable_marker_count', 'excel_error_count']
display(columns.loc[columns[marker_columns].sum(axis=1) > 0, ['reporting_period', 'sheet', 'column', 'semantic_type'] + marker_columns])
display(formats.groupby(['reporting_period', 'number_format_class'])['formatted_cell_count'].sum().unstack(fill_value=0))

    reporting_period  ... missing_percent
492          2023-H2  ...        100.0000
737          2025-H1  ...         96.6914
808          2025-H2  ...         89.7436
722          2025-H1  ...         89.5522
84           2021-H1  ...         88.2353
165          2021-H2  ...         88.2353
246          2022-H1  ...         88.2353
333          2022-H2  ...         88.2353
415          2023-H1  ...         88.2353
580          2024-H1  ...         88.2353
721          2025-H1  ...         88.0597
724          2025-H1  ...         86.5672
807          2025-H2  ...         85.8974
99           2021-H2  ...         85.7143
810          2025-H2  ...         84.6154
100          2021-H2  ...         84.1270
13           2021-H1  ...         83.5443
430          2023-H2  ...         83.5443
513          2024-H1  ...         83.1169
348          2023-H1  ...         82.6667
431          2023-H2  ...         82.2785
512          2024-H1  ...         81.8182
351          2023-H1  ...         81.3333
207          2022-H1  ...         81.3084
14           2021-H1  ...         81.0127

[25 rows x 7 columns]

semantic_type     decimal_like  empty  ...  mixed  percentage
reporting_period                       ...
2021-H1                      9      0  ...      0          19
2021-H2                      9      0  ...      0          15
2022-H1                      9      0  ...      0          15
2022-H2                      9      0  ...      0          18
2023-H1                      9      0  ...      0          16
2023-H2                      9      1  ...      1          15
2024-H1                      9      0  ...      0          16
2024-H2                      9      0  ...      0          16
2025-H1                      9      0  ...      0          16
2025-H2                      9      0  ...      0          19

[10 rows x 6 columns]

    reporting_period  ... excel_error_count
736          2025-H1  ...                 0
782          2025-H2  ...                 2
802          2025-H2  ...                 2

[3 rows x 8 columns]

number_format_class  date  general  number  percentage
reporting_period
2021-H1                 0    11007     152        4394
2021-H2                 0     8473     187        1137
2022-H1                 0    10609     181        1798
2022-H2               239    10968     174        2445
2023-H1                 0     8053    1669        1338
2023-H2                 0     8866     557        1207
2024-H1                 0     9079     493        1297
2024-H2                 0     8658     485        1277
2025-H1                 0    33909     469        1247
2025-H2                 0     7769     963        1914

## Cross-period schema changes and warnings

In [7]:
display(schema.groupby(['current_period', 'change_type']).size().unstack(fill_value=0))
display(schema)
display(warnings)

change_type     column_added  ...  storage_dtype_changed
current_period                ...
2021-H2                    5  ...                     26
2022-H1                    5  ...                     15
2022-H2                    7  ...                     10
2023-H1                    2  ...                     24
2023-H2                    7  ...                      2
2024-H1                    0  ...                      1
2024-H2                    0  ...                      1
2025-H1                    0  ...                      2
2025-H2                    5  ...                      1

[9 rows x 9 columns]

   previous_period  ...  review_status
0          2021-H1  ...  manual_review
1          2021-H1  ...  manual_review
2          2021-H1  ...  informational
3          2021-H1  ...  informational
4          2021-H1  ...  informational
5          2021-H1  ...  informational
6          2021-H1  ...  informational
7          2021-H1  ...  manual_review
8          2021-H1  ...  manual_review
9          2021-H1  ...  manual_review
10         2021-H1  ...  manual_review
11         2021-H1  ...  manual_review
12         2021-H1  ...  manual_review
13         2021-H1  ...  manual_review
14         2021-H1  ...  manual_review
15         2021-H1  ...  manual_review
16         2021-H1  ...  manual_review
17         2021-H1  ...  manual_review
18         2021-H1  ...  manual_review
19         2021-H1  ...  manual_review
20         2021-H1  ...  manual_review
21         2021-H1  ...  manual_review
22         2021-H1  ...  manual_review
23         2021-H1  ...  manual_review
24         2021-H1  ...  manual_review
25         2021-H1  ...  manual_review
26         2021-H1  ...  manual_review
27         2021-H1  ...  manual_review
28         2021-H1  ...  manual_review
29         2021-H1  ...  informational

[30 rows x 21 columns]
[Preview limited to 30 of 234 rows]

                                   workbook  ...                                            message
0   firm-level-complaints-data-2021-h1.xlsx  ...  Preferred convention is fca_firm_level_complai...
1   firm-level-complaints-data-2021-h1.xlsx  ...   Selected header row 9; review ranked candidates.
2   firm-level-complaints-data-2021-h2.xlsx  ...  Preferred convention is fca_firm_level_complai...
3   firm-level-complaints-data-2021-h2.xlsx  ...   Selected header row 9; review ranked candidates.
4   firm-level-complaints-data-2022-h1.xlsx  ...  Preferred convention is fca_firm_level_complai...
5   firm-level-complaints-data-2022-h1.xlsx  ...   Selected header row 9; review ranked candidates.
6   firm-level-complaints-data-2022-h2.xlsx  ...  Preferred convention is fca_firm_level_complai...
7   firm-level-complaints-data-2022-h2.xlsx  ...   Selected header row 9; review ranked candidates.
8   firm-level-complaints-data-2023-h1.xlsx  ...  Preferred convention is fca_firm_level_complai...
9   firm-level-complaints-data-2023-h1.xlsx  ...  Excel declares 1048571 rows but values end at ...
10  firm-level-complaints-data-2023-h1.xlsx  ...   Selected header row 9; review ranked candidates.
11  firm-level-complaints-data-2023-h2.xlsx  ...  Preferred convention is fca_firm_level_complai...
12  firm-level-complaints-data-2023-h2.xlsx  ...  Column 'unnamed_9' contains mixed substantive ...
13  firm-level-complaints-data-2024-h1.xlsx  ...  Preferred convention is fca_firm_level_complai...
14  firm-level-complaints-data-2024-h1.xlsx  ...   Selected header row 9; review ranked candidates.
15  firm-level-complaints-data-2024-h2.xlsx  ...  Preferred convention is fca_firm_level_complai...
16  firm-level-complaints-data-2025-h1.xlsx  ...  Preferred convention is fca_firm_level_complai...
17  firm-level-complaints-data-2025-h1.xlsx  ...  Column 'Other trading names' contains 1 non-nu...
18  firm-level-complaints-data-2025-h2.xlsx  ...  Preferred convention is fca_firm_level_complai...
19  firm-level-complaints-data-2025-h2.xlsx  ...      Column 'Grand Total' contains 2 Excel errors.
20  firm-level-complaints-data-2025-h2.xlsx  ...      Column 'Grand Total' contains 2 Excel errors.

[21 rows x 6 columns]

## Review gate

Before extraction or cleaning begins, confirm candidate headers, possible renames, sheet-role mappings, product definitions, total/note rows, and percentage/currency formats. Possible renames are heuristic suggestions, not automatic transformations.